In [184]:
import pandas as pd
import numpy as np

In [185]:
train = pd.read_csv('/Users/sathishkumars/Documents/Anaconda-Python/Hackathons/SAWE/train.csv')
test = pd.read_csv('/Users/sathishkumars/Documents/Anaconda-Python/Hackathons/SAWE/test.csv')
submission = pd.read_csv('/Users/sathishkumars/Documents/Anaconda-Python/Hackathons/SAWE/submission.csv')
train.shape, test.shape

((44100, 4), (18900, 3))

In [186]:
train.head(20)

ID           author                                             Review  \
0   39467    rayinstirling  Today I'm working on my &quot;Quirky Q&quot; c...   
1   30154      DirtyRose17  @ShannonElizab dont ya know? people love the h...   
2   16767    yoliemichelle  ughhh rejected from the 09 mediation program. ...   
3    9334      jayamelwani     @petewentz im so jealous. i want an octo drive   
4   61178       aliisanoun  I remember all the hype around this movie when...   
5   54688    empressjazzy1  I liked this quite a bit but I have friends th...   
6   34838          lorrief  loving that spring definitely seems to be here...   
7   28520          GE0RGIE                       @jeg007jeg yay  coutch:couch   
8   31974   BrandonCarlson  Working on the store's Facebook group, getting...   
9   14323       allshookup  @falselove OH THAT'S GOOD! My top 4 are: The H...   
10  58682        voidstuff  This was an impulse pick up for me from the lo...   
11  21406            eBeth  @ShoeGal007 I always love help propping up the...   
12  61255        jennac0re  Who can watch a movie, look at Lucy Liu and no...   
13  43740        HDrobiarz  I enjoyed it. There you go, I said it again. I...   
14  38359           harisn  My phone is ultra fast now with all the latest...   
15  11824  sheiknizamuddin  Went to sleep and there is a power cut in Noid...   
16  29840         JillianG                                           Relaxing   
17  40347           sue_jr                      The kids are very cool too.     
18  39808     NUMB3R1D1VAA  omg.. srry guys i'm not 2 focused this morning...   
19  35285            nilla  @khasabadmemory thanks for teaching me how to ...   

    Sentiment  
0           2  
1           1  
2           0  
3           0  
4           0  
5           2  
6           2  
7           2  
8           2  
9           0  
10          0  
11          1  
12          2  
13          2  
14          2  
15          1  
16          2  
17          2  
18          1  
19          2

In [187]:
test.head(10)

ID          author                                             Review
0  29536    nathantbaker  @amyswarren ahhh yay! I'm getting into it. Kno...
1  13442    Umatter2Chtr  @DeliverImHungry You are right.  If you ordere...
2  54697  bella_cullen_4  I'd heard a lot of bad things about this film ...
3   7007   marviemorales  I miss the old... HA, HA. I can't tell that pe...
4  34410         phaoloo                                 @dharshana anytime
5  60492    GreenEyes270  "Birth of the Beatles", for being a US televis...
6   8416       heymckate  @eep2001 Might have to cancel our Disney trip ...
7   9352        Njonesey  ok so everyone is out an im stuck in bored and...
8  57053         squelsh  The only reason "The Norliss Tapes" deserves A...
9  32943      dudeman718            @jmstewart0220 I know!!  It was great!!

In [188]:
train['Sentiment'].value_counts()

0    19299
2    18733
1     6068
Name: Sentiment, dtype: int64

In [189]:
train.isnull().sum()

ID           0
author       0
Review       0
Sentiment    0
dtype: int64

In [190]:
test.isnull().sum()

ID        0
author    0
Review    0
dtype: int64

In [191]:
train_text = train['Review']
test_text = test['Review']

In [192]:
train_text

0        Today I'm working on my &quot;Quirky Q&quot; c...
1        @ShannonElizab dont ya know? people love the h...
2        ughhh rejected from the 09 mediation program. ...
3           @petewentz im so jealous. i want an octo drive
4        I remember all the hype around this movie when...
                               ...                        
44095    "The Mother" is a weird low-budget movie, touc...
44096    It started off weird, the middle was weird, an...
44097    I was amazed at the quick arrival of the two o...
44098    Attractive Marjorie(Farrah Fawcett)lives in fe...
44099    @_refugee_ /me gets &quot;Your video will star...
Name: Review, Length: 44100, dtype: object

In [323]:
data = pd.concat([train_text, test_text], ignore_index = True, sort = True)

In [327]:
data

0        today im work quotquirki qquot cue mayb becom ...
1                    dont ya know peopl love human societi
2                  ughhh reject 09 mediat program suckssss
3                                im jealou want octo drive
4        rememb hype around movi aaliyah kill fan ms ri...
                               ...                        
62995    This show comes up with interesting locations ...
62996                     haha. i love you too aimeeeeeee!
62997                                    another rainy day
62998    wanted to sleep but a friend from Denmark just...
62999    Has roughly cleaned his room, and now is headi...
Name: Review, Length: 63000, dtype: object

# Data Pre-processing

In [225]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/sathishkumars/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     /Users/sathishkumars/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [226]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/sathishkumars/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [227]:
import re
import emoji
import string
from nltk.corpus import stopwords
from nltk import word_tokenize
from nltk.stem import PorterStemmer
stop = set(stopwords.words('english'))
exclude = set(string.punctuation)
porter = PorterStemmer()
emojis = emoji.UNICODE_EMOJI

In [333]:
def remove_URL(text):
    URL = re.compile(r'https?://\S+|www/./S+')
    return URL.sub(r'',text)
def remove_handles(text):
    handle = re.compile(r'@\S+')
    return handle.sub(r'',text)
def remove_HTML(text):
    HTML = re.compile(r'<.*?>')
    return HTML.sub(r'', text)
def remove_punctuation(text):
    return ''.join([ch for ch in text if ch not in exclude])
def remove_stopwords(text):
    return ' '.join([x for x in word_tokenize(text) if x not in stop])
def remove_emojis(text):
    emojilist = [x for x in text if x in emojis]
    return ''.join([ch for ch in text if ch not in emojilist])
def stemming(text):
    return ' '.join([porter.stem(x) for x in word_tokenize(text)])
def remove_spaces(text):
    text = text.strip()
    text = text.split()
    return ' '.join(text)

In [334]:
def data_preprocessing(text):
    text = text.apply(lambda x: x.lower())
    text = text.apply(lambda x: remove_URL(x))
    text = text.apply(lambda x: remove_handles(x))
    text = text.apply(lambda x: remove_HTML(x))
    text = text.apply(lambda x: remove_emojis(x))
    text = text.apply(lambda x: remove_punctuation(x))
    text = text.apply(lambda x: remove_spaces(x))
    text = text.apply(lambda x: remove_stopwords(x))
    text = text.apply(lambda x: stemming(x))
    return text

In [230]:
train_text = data_preprocessing(train_text)

In [143]:
test_text = data_preprocessing(test_text)

In [335]:
data = data_preprocessing(data)

In [144]:
test_text

0                              ahhh yay im get knockin lot
1                         right order static ip set apolog
2        id heard lot bad thing film see thought neg co...
3                     miss old ha ha cant tell person name
4                                                   anytim
                               ...                        
18895    show come interest locat fast travel channel b...
18896                                  haha love aimeeeeee
18897                                      anoth raini day
18898                    want sleep friend denmark poke im
18899                   roughli clean room head pablo read
Name: Review, Length: 18900, dtype: object

# Modelling

In [193]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words = 1000)
from keras.preprocessing.sequence import pad_sequences

In [336]:
max_seq_length = 1000
tokenizer.fit_on_texts(data)
train_seq = tokenizer.texts_to_sequences(train_text)
test_seq = tokenizer.texts_to_sequences(test_text)
train_seq_pad = pad_sequences(train_seq, maxlen = max_seq_length)
test_seq_pad = pad_sequences(test_seq, maxlen = max_seq_length)

In [338]:
index = tokenizer.word_index

In [339]:
len(index) #After pre-processing

193111

In [331]:
len(index)

171779

In [46]:
index #After pre processing

{'movi': 1,
 'film': 2,
 'one': 3,
 'like': 4,
 'good': 5,
 'get': 6,
 'time': 7,
 'make': 8,
 'see': 9,
 'watch': 10,
 'charact': 11,
 'would': 12,
 'even': 13,
 'go': 14,
 'realli': 15,
 'stori': 16,
 'love': 17,
 'look': 18,
 'well': 19,
 'much': 20,
 'show': 21,
 'scene': 22,
 'dont': 23,
 'great': 24,
 'think': 25,
 'im': 26,
 'bad': 27,
 'peopl': 28,
 'end': 29,
 'work': 30,
 'way': 31,
 'know': 32,
 'also': 33,
 'play': 34,
 'first': 35,
 'thing': 36,
 'act': 37,
 'could': 38,
 'say': 39,
 'made': 40,
 'want': 41,
 'day': 42,
 'come': 43,
 'seem': 44,
 'take': 45,
 'tri': 46,
 'never': 47,
 'littl': 48,
 'mani': 49,
 'feel': 50,
 'best': 51,
 'seen': 52,
 'two': 53,
 'year': 54,
 'still': 55,
 'actor': 56,
 'plot': 57,
 'back': 58,
 'ever': 59,
 'better': 60,
 'life': 61,
 'got': 62,
 'give': 63,
 'man': 64,
 'use': 65,
 'cant': 66,
 'find': 67,
 'someth': 68,
 'actual': 69,
 'new': 70,
 'perform': 71,
 'lot': 72,
 'didnt': 73,
 'part': 74,
 'interest': 75,
 'guy': 76,
 'though'

In [332]:
index

{'the': 1,
 'a': 2,
 'and': 3,
 'to': 4,
 'of': 5,
 'is': 6,
 'film': 7,
 'i': 8,
 'br': 9,
 'in': 10,
 'it': 11,
 'that': 12,
 'this': 13,
 'movi': 14,
 'one': 15,
 'like': 16,
 'was': 17,
 'for': 18,
 'with': 19,
 'as': 20,
 'but': 21,
 'movie': 22,
 'good': 23,
 'on': 24,
 'you': 25,
 'time': 26,
 'get': 27,
 'see': 28,
 'not': 29,
 'have': 30,
 'are': 31,
 'would': 32,
 'even': 33,
 'he': 34,
 'be': 35,
 'make': 36,
 'his': 37,
 'watch': 38,
 'well': 39,
 'at': 40,
 'all': 41,
 'much': 42,
 'go': 43,
 'so': 44,
 'great': 45,
 'love': 46,
 'bad': 47,
 'by': 48,
 'an': 49,
 'think': 50,
 'my': 51,
 'they': 52,
 'from': 53,
 'also': 54,
 'who': 55,
 'first': 56,
 'just': 57,
 'way': 58,
 'show': 59,
 'there': 60,
 'know': 61,
 'scene': 62,
 'made': 63,
 'look': 64,
 'could': 65,
 'out': 66,
 'work': 67,
 "it's": 68,
 'or': 69,
 'charact': 70,
 'end': 71,
 'what': 72,
 'about': 73,
 'her': 74,
 'if': 75,
 'realli': 76,
 'day': 77,
 'say': 78,
 'has': 79,
 'thing': 80,
 'stori': 81,
 'n

# Importing Glove Vectors 

In [47]:
word_to_vec_map = {}
with open('/Users/sathishkumars/Documents/Anaconda-Python/glove/glove.6B.50d.txt') as file:
    for line in file:
        values = line.strip().split()
        curr_word = values[0]
        word_to_vec_map[curr_word] = np.array(values[1:], dtype = np.float64)
len(word_to_vec_map)

400000

In [48]:
dim = 50

In [340]:
embedding_matrix = np.zeros((len(index) + 1, dim))
for word, i in index.items():
    temp = word_to_vec_map.get(word)
    if temp is not None:
        embedding_matrix[i] = temp

In [ ]:
embedding_matrix

# Training data

In [198]:
from keras.utils import to_categorical

In [341]:
Y = to_categorical(train['Sentiment'], num_classes = 3)

In [342]:
X = train_seq_pad

In [343]:
from sklearn.model_selection import train_test_split

In [344]:
xTrain, xTest, yTrain, yTest = train_test_split(X, Y, test_size = 0.2, random_state = 21)

# 1) Bidirectional LSTM

In [153]:
from keras.models import Sequential 
from keras.layers import Embedding, Bidirectional, LSTM, Dropout, Dense, GlobalMaxPooling1D

In [345]:
embed_layer = Embedding(len(index) +1, dim, input_length = max_seq_length, weights = [embedding_matrix])

In [346]:
model = Sequential()
model.add(embed_layer)
model.add(Bidirectional(LSTM(dim, return_sequences = True, dropout = 0.1, recurrent_dropout = 0.1)))
model.add(GlobalMaxPooling1D())
model.add(Dense(50, activation = 'relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation = 'softmax'))

In [347]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 1000, 50)          9655600   
_________________________________________________________________
bidirectional_3 (Bidirection (None, 1000, 100)         40400     
_________________________________________________________________
global_max_pooling1d_3 (Glob (None, 100)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 50)                5050      
_________________________________________________________________
dropout_3 (Dropout)          (None, 50)                0         
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 153       
Total params: 9,701,203
Trainable params: 9,701,203
Non-trainable params: 0
____________________________________________

In [348]:
model.compile(loss = 'binary_crossentropy', optimizer = 'Adam', metrics = ['accuracy'])

In [349]:
history = model.fit(xTrain, yTrain, epochs = 2, batch_size = 128, validation_data = (xTest, yTest))

Epoch 1/2
276/276 [==============================] - 479s 2s/step - loss: 0.5572 - accuracy: 0.5163 - val_loss: 0.4707 - val_accuracy: 0.6300
Epoch 2/2
276/276 [==============================] - 524s 2s/step - loss: 0.4619 - accuracy: 0.6418 - val_loss: 0.4625 - val_accuracy: 0.6374


In [350]:
pred = model.predict(test_seq_pad)

In [351]:
pred.shape

(18900, 3)

In [352]:
pred

array([[5.63176632e-01, 1.24820918e-01, 3.12002450e-01],
       [5.76375782e-01, 1.11542486e-01, 3.12081695e-01],
       [9.02809799e-01, 6.89583190e-04, 9.65006277e-02],
       ...,
       [2.89741457e-01, 2.82760859e-01, 4.27497715e-01],
       [5.02640843e-01, 1.24581002e-01, 3.72778118e-01],
       [2.30683640e-01, 1.54686853e-01, 6.14629447e-01]], dtype=float32)

In [161]:
pred

array([[3.8282117e-01, 2.7837554e-01, 3.3880329e-01],
       [2.9168296e-01, 4.0305918e-01, 3.0525792e-01],
       [9.9865627e-01, 6.0951574e-05, 1.2827138e-03],
       ...,
       [2.8496417e-01, 3.7443748e-01, 3.4059837e-01],
       [6.2694788e-01, 1.8850578e-01, 1.8454634e-01],
       [2.3527084e-01, 3.8261887e-01, 3.8211036e-01]], dtype=float32)

# 2) Logistic Regression

In [232]:
X1 = train_seq_pad
Y1 = train['Sentiment']

In [233]:
x1Train, x1Test, y1Train, y1Test = train_test_split(X1, Y1, test_size = 0.2, random_state = 21)

In [205]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()

In [211]:
from sklearn.metrics import accuracy_score, log_loss

In [234]:
LR.fit(x1Train, y1Train)

/Users/sathishkumars/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
pred_LR = LR.predict(x1Test)

In [236]:
accuracy_score(y1Test, pred_LR)

0.45068027210884354

In [224]:
LR.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

# Naive Bayees Classifier

In [217]:
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
mNB = MultinomialNB()
bNB = BernoulliNB()

In [237]:
mNB.fit(x1Train, y1Train)

MultinomialNB()

In [238]:
pred_mNB = mNB.predict(x1Test)

In [239]:
accuracy_score(y1Test, pred_mNB)

0.30113378684807257

In [240]:
bNB.fit(x1Train, y1Train)

BernoulliNB()

In [241]:
pred_bNB = bNB.predict(x1Test)

In [242]:
accuracy_score(y1Test, pred_bNB)

0.30578231292517005

# Ensembling

In [353]:
pred_LSTM = np.argmax(pred, axis = 1)

In [280]:
pred_LR1 = LR.predict_proba(test_seq_pad)
pred_mNB1 = mNB.predict_proba(test_seq_pad)
pred_bNB1 = bNB.predict_proba(test_seq_pad)

In [302]:
pred_test = (pred_LR1 + pred_mNB1 + pred_bNB1 + pred) / 4

In [303]:
pred_test

array([[1.93998008e-01, 6.28593661e-01, 1.77408331e-01],
       [2.53264726e-01, 1.38812778e-01, 6.07922511e-01],
       [6.32065438e-01, 1.52379098e-05, 3.67919309e-01],
       ...,
       [1.61747586e-01, 6.65764497e-01, 1.72487925e-01],
       [2.51426038e-01, 3.32196737e-01, 4.16377225e-01],
       [1.58920840e-01, 6.55051313e-01, 1.86027866e-01]])

In [304]:
len(pred_test)

18900

In [305]:
pred_test = np.argmax(pred_test, axis = 1)

In [306]:
pred_test

array([1, 2, 0, ..., 1, 2, 1])

In [307]:
len(pred_index)

18900

In [356]:
pred_LSTM

array([0, 0, 0, ..., 2, 0, 2])

In [354]:
predf = np.zeros((18900,3))

In [355]:
predf.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [357]:
for idx, val in enumerate(pred_LSTM):
    predf[idx,val] = 1

In [358]:
predf = predf.astype(int)

In [359]:
predf

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1]])

In [374]:
my_submission = pd.DataFrame(predf , columns = ['Negative_0','Neutral_1','Positive_2'])

In [371]:
my_submission = pd.get_dummies(my_submission4)

In [375]:
my_submission.to_csv('my_submission.csv', index = False)

In [373]:
my_submission

Negative_0  Neutral_1  Positive_2
0               1          0           0
1               1          0           0
2               1          0           0
3               1          0           0
4               0          1           0
...           ...        ...         ...
18895           0          0           1
18896           0          0           1
18897           0          0           1
18898           1          0           0
18899           0          0           1

[18900 rows x 3 columns]

In [76]:
submission

Negative_0  Neutral_1  Positive_2
0               0          1           0
1               1          0           0
2               0          0           1
3               0          0           0
4               0          0           0
...           ...        ...         ...
18895           0          0           0
18896           0          0           0
18897           0          0           0
18898           0          0           0
18899           0          0           0

[18900 rows x 3 columns]

In [177]:
test['Review'][:5]

0    @amyswarren ahhh yay! I'm getting into it. Kno...
1    @DeliverImHungry You are right.  If you ordere...
2    I'd heard a lot of bad things about this film ...
3    I miss the old... HA, HA. I can't tell that pe...
4                                   @dharshana anytime
Name: Review, dtype: object

In [179]:
my_submission1.head(5)

Negative_0  Neutral_1  Positive_2
0           1          0           0
1           0          1           0
2           1          0           0
3           1          0           0
4           0          1           0