In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os

In [57]:
train = pd.read_csv(os.getcwd()+'/train.csv')
test = pd.read_csv(os.getcwd()+'/test.csv')
submission = pd.read_csv(os.getcwd()+'/submission.csv')
train.shape, test.shape

((7443, 21), (4008, 20))

In [58]:
pd.set_option('display.max_columns',25)

In [59]:
train.head()

season      date  league_id                league                Team 1  \
0    2019  01/03/19       1979  Chinese Super League       Shandong Luneng   
1    2019  01/03/19       1979  Chinese Super League    Shanghai Greenland   
2    2019  01/03/19       1979  Chinese Super League  Guangzhou Evergrande   
3    2019  01/03/19       1979  Chinese Super League            Wuhan Zall   
4    2019  01/03/19       1979  Chinese Super League       Chongqing Lifan   

               Team2   SPI1   SPI2  proj_score1  proj_score2  importance1  \
0      Guizhou Renhe  48.22  37.83         1.75         0.84         45.9   
1      Shanghai SIPG  39.81  60.08         1.22         1.89         25.6   
2  Tianjin Quanujian  65.59  39.99         2.58         0.62         77.1   
3      Beijing Guoan  32.25  54.82         1.10         1.79         35.8   
4       Guangzhou RF  38.24  40.45         1.57         1.24         26.2   

   importance2  score1  score2   xg1   xg2  nsxg1  nsxg2  adj_score1  \
0         22.1     1.0     0.0  1.39  0.26   2.05   0.54        1.05   
1         63.4     0.0     4.0  0.57  2.76   0.80   1.50        0.00   
2         28.8     3.0     0.0  0.49  0.45   1.05   0.75        3.15   
3         58.9     0.0     1.0  1.12  0.97   1.51   0.94        0.00   
4         21.3     2.0     2.0  2.77  3.17   1.05   2.08        2.10   

   adj_score2  Outcome  
0        0.00        1  
1        3.26        0  
2        0.00        1  
3        1.05        0  
4        2.10        1

In [60]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7443 entries, 0 to 7442
Data columns (total 21 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   season       7443 non-null   int64  
 1   date         7443 non-null   object 
 2   league_id    7443 non-null   int64  
 3   league       7443 non-null   object 
 4   Team 1       7443 non-null   object 
 5   Team2        7443 non-null   object 
 6   SPI1         7443 non-null   float64
 7   SPI2         7443 non-null   float64
 8   proj_score1  7443 non-null   float64
 9   proj_score2  7443 non-null   float64
 10  importance1  2527 non-null   float64
 11  importance2  2527 non-null   float64
 12  score1       2643 non-null   float64
 13  score2       2643 non-null   float64
 14  xg1          1715 non-null   float64
 15  xg2          1715 non-null   float64
 16  nsxg1        1715 non-null   float64
 17  nsxg2        1715 non-null   float64
 18  adj_score1   1715 non-null   float64
 19  adj_sc

In [61]:
train['flag'] = 'train'
test['flag'] = 'test'
data = pd.concat([train, test], ignore_index = False, sort = True)

In [62]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

In [63]:
data['day'] = data['date'].apply(lambda x: x[0:2]).astype(int)
data['month'] = data['date'].apply(lambda x: x[3:5]).astype(int)
data.drop(['date', 'league'], axis = 1, inplace = True)
data['Team 1'] = LE.fit_transform(data['Team 1'])
data['Team2'] = LE.fit_transform(data['Team2'])   

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11451 entries, 0 to 4007
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Outcome      7443 non-null   float64
 1   SPI1         11451 non-null  float64
 2   SPI2         11451 non-null  float64
 3   Team 1       11451 non-null  int64  
 4   Team2        11451 non-null  int64  
 5   adj_score1   1715 non-null   float64
 6   adj_score2   1715 non-null   float64
 7   flag         11451 non-null  object 
 8   importance1  2527 non-null   float64
 9   importance2  2527 non-null   float64
 10  league_id    11451 non-null  int64  
 11  nsxg1        1715 non-null   float64
 12  nsxg2        1715 non-null   float64
 13  proj_score1  11451 non-null  float64
 14  proj_score2  11451 non-null  float64
 15  score1       2643 non-null   float64
 16  score2       2643 non-null   float64
 17  season       11451 non-null  int64  
 18  xg1          1715 non-null   float64
 19  xg2  

In [66]:
train.columns

Index(['season', 'date', 'league_id', 'league', 'Team 1', 'Team2', 'SPI1',
       'SPI2', 'proj_score1', 'proj_score2', 'importance1', 'importance2',
       'score1', 'score2', 'xg1', 'xg2', 'nsxg1', 'nsxg2', 'adj_score1',
       'adj_score2', 'Outcome', 'flag'],
      dtype='object')

In [67]:
columns =['season', 'league_id', 'Team 1', 'Team2', 'SPI1', 'SPI2', 'proj_score1',
       'proj_score2', 'importance1', 'importance2', 'score1', 'score2', 'xg1',
       'xg2', 'nsxg1', 'nsxg2', 'adj_score1', 'adj_score2', 'month', 'day']

In [68]:
df_d = data[columns]

In [69]:
df_d1 = knn.fit(df_d)

In [70]:
train = data[data['flag'] == 'train']
test = data[data['flag'] == 'test']

In [71]:
df_train = train.drop(['flag', 'Outcome'], axis = 1)

In [72]:
df_train

SPI1   SPI2  Team 1  Team2  adj_score1  adj_score2  importance1  \
0     48.22  37.83     531    262        1.05        0.00         45.9   
1     39.81  60.08     532    533        0.00        3.26         25.6   
2     65.59  39.99     258    589        3.15        0.00         77.1   
3     32.25  54.82     649     73        0.00        1.05         35.8   
4     38.24  40.45     138    259        2.10        2.10         26.2   
...     ...    ...     ...    ...         ...         ...          ...   
7438  34.05  33.76     311      0         NaN         NaN          NaN   
7439  36.73  36.11     496    502         NaN         NaN          NaN   
7440  12.97  23.59     388    426         NaN         NaN          NaN   
7441  11.76  18.07     605     81         NaN         NaN          NaN   
7442  25.89  10.75     359     67         NaN         NaN          NaN   

      importance2  league_id  nsxg1  nsxg2  proj_score1  proj_score2  score1  \
0            22.1       1979   2.05   0.54         1.75         0.84     1.0   
1            63.4       1979   0.80   1.50         1.22         1.89     0.0   
2            28.8       1979   1.05   0.75         2.58         0.62     3.0   
3            58.9       1979   1.51   0.94         1.10         1.79     0.0   
4            21.3       1979   1.05   2.08         1.57         1.24     2.0   
...           ...        ...    ...    ...          ...          ...     ...   
7438          NaN       1846    NaN    NaN         1.39         1.19     NaN   
7439          NaN       1846    NaN    NaN         1.67         1.44     NaN   
7440          NaN       1983    NaN    NaN         1.05         1.50     NaN   
7441          NaN       1983    NaN    NaN         1.22         1.46     NaN   
7442          NaN       1983    NaN    NaN         1.41         0.59     NaN   

      score2  season   xg1   xg2  day  month  
0        0.0    2019  1.39  0.26    1      3  
1        4.0    2019  0.57  2.76    1      3  
2        0.0    2019  0.49  0.45    1      3  
3        1.0    2019  1.12  0.97    1      3  
4        2.0    2019  2.77  3.17    1      3  
...      ...     ...   ...   ...  ...    ...  
7438     NaN    2021   NaN   NaN   12     12  
7439     NaN    2021   NaN   NaN   12     12  
7440     NaN    2021   NaN   NaN   14     12  
7441     NaN    2021   NaN   NaN   14     12  
7442     NaN    2021   NaN   NaN   14     12  

[7443 rows x 20 columns]

In [73]:
df_train = knn.transform(df_train)

In [74]:
X = df_train
Y = train['Outcome']

In [97]:
from imblearn.over_sampling import RandomOverSampler
oversample = RandomOverSampler()

In [98]:
X1, Y1 = oversample.fit_resample(X, Y)

In [99]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(X1, Y1, test_size = 0.2, random_state = 21)
xTrain.shape, xTest.shape, yTrain.shape, yTest.shape

((8112, 20), (2028, 20), (8112,), (2028,))

In [100]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
LR = LogisticRegression()
RF = RandomForestClassifier()
xgb = XGBClassifier()

In [101]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier()

In [102]:
LR.fit(xTrain, yTrain)

/Users/sathishkumars/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [103]:
pred_test = LR.predict(xTest)

In [104]:
from sklearn.metrics import accuracy_score, log_loss

In [105]:
print(accuracy_score(pred_test, yTest))

0.9452662721893491


In [106]:
RF.fit(xTrain, yTrain)
pred_RF = RF.predict(xTest)
print(accuracy_score(pred_RF, yTest))

0.9901380670611439


In [107]:
xgb.fit(xTrain, yTrain)
pred_xgb = xgb.predict(xTest)
print(accuracy_score(pred_xgb, yTest))

/Users/sathishkumars/opt/anaconda3/lib/python3.8/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[15:24:48] WARNING: /opt/concourse/worker/volumes/live/7a2b9f41-3287-451b-6691-43e9a6c0910f/volume/xgboost-split_1619728204606/work/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
0.9960552268244576


In [108]:
lgb.fit(xTrain, yTrain)
pred_lgb = lgb.predict(xTest)
print(accuracy_score(pred_lgb, yTest))

0.9965483234714004


In [109]:
test

Outcome   SPI1   SPI2  Team 1  Team2  adj_score1  adj_score2  flag  \
0         NaN  79.65  74.06      40    641         NaN         NaN  test   
1         NaN  74.19  71.14     100    648         NaN         NaN  test   
2         NaN  60.67  71.45     411     45         NaN         NaN  test   
3         NaN  76.88  79.06     333    598         NaN         NaN  test   
4         NaN  63.53  85.58      96    362         NaN         NaN  test   
...       ...    ...    ...     ...    ...         ...         ...   ...   
4003      NaN  41.51  48.12     332     25         NaN         NaN  test   
4004      NaN  26.77  33.53       5    176         NaN         NaN  test   
4005      NaN  26.62  28.65     378    235         NaN         NaN  test   
4006      NaN  33.74  30.32     557    324         NaN         NaN  test   
4007      NaN  29.70  30.25     478    480         NaN         NaN  test   

      importance1  importance2  league_id  nsxg1  nsxg2  proj_score1  \
0             NaN          NaN       2411    NaN    NaN         1.67   
1             NaN          NaN       2411    NaN    NaN         1.35   
2             NaN          NaN       2411    NaN    NaN         1.18   
3             NaN          NaN       2411    NaN    NaN         1.52   
4             NaN          NaN       2411    NaN    NaN         0.95   
...           ...          ...        ...    ...    ...          ...   
4003          NaN          NaN       1871    NaN    NaN         1.40   
4004          NaN          NaN       1871    NaN    NaN         1.17   
4005          NaN          NaN       1871    NaN    NaN         1.31   
4006          NaN          NaN       1871    NaN    NaN         1.33   
4007          NaN          NaN       1871    NaN    NaN         1.38   

      proj_score2  score1  score2  season  xg1  xg2  day  month  
0            1.19     NaN     NaN    2021  NaN  NaN   14     12  
1            0.98     NaN     NaN    2021  NaN  NaN   14     12  
2            1.49     NaN     NaN    2021  NaN  NaN   14     12  
3            1.44     NaN     NaN    2021  NaN  NaN   14     12  
4            1.92     NaN     NaN    2021  NaN  NaN   14     12  
...           ...     ...     ...     ...  ...  ...  ...    ...  
4003         1.39     NaN     NaN    2021  NaN  NaN   29      5  
4004         1.18     NaN     NaN    2021  NaN  NaN   29      5  
4005         1.14     NaN     NaN    2021  NaN  NaN   29      5  
4006         0.87     NaN     NaN    2021  NaN  NaN   29      5  
4007         1.19     NaN     NaN    2021  NaN  NaN   29      5  

[4008 rows x 22 columns]

In [110]:
test = test.drop(['Outcome', 'flag'], axis = 1)

In [111]:
df_test = knn.transform(test)

In [39]:
predf = LR.predict(df_test)
predf = predf.astype(int)
predf

array([1, 1, 0, ..., 1, 1, 1])

In [112]:
predf_xgb = xgb.predict(df_test)
predf_xgb = predf_xgb.astype(int)
predf_xgb

array([1, 1, 0, ..., 1, 1, 1])

In [113]:
predf_lgb = lgb.predict(df_test)
predf_lgb = predf_lgb.astype(int)
predf_lgb

array([1, 1, 0, ..., 1, 1, 1])

In [50]:
import statistics

In [114]:
mysubmission4 = pd.DataFrame(predf_lgb, columns = ['Outcome'] )

In [130]:
mysubmission.value_counts()

Outcome
1          2832
0          1176
dtype: int64

In [131]:
mysubmission1.value_counts()

Outcome
1          2715
0          1293
dtype: int64

In [204]:
mysubmission2.value_counts()

Outcome
1          2704
0          1304
dtype: int64

In [41]:
mysubmission3.value_counts()

Outcome
1          2780
0          1228
dtype: int64

In [115]:
mysubmission4.value_counts()

Outcome
1          2704
0          1304
dtype: int64

In [77]:
submission

Outcome
0           0
1           0
2           0
3           0
4           0
...       ...
4003        0
4004        0
4005        0
4006        0
4007        0

[4008 rows x 1 columns]

In [116]:
mysubmission4.to_csv('mysubmission4.csv', index = False)